site_name: Winterbloom Order Queue
copyright: "Â© 2020 Winterbloom, licensed under Creative Commons CC BY-SA 4.0"
repo_url: "https://github.com/wntrblm/queue.winterbloom.com"
edit_uri: edit/main/user_guide/docs
site_url: https://queue.winterbloom.com
theme:
    name: winterbloom
markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - toc:
          permalink: "#"
          toc_depth: 2-3
    - pymdownx.highlight:
          use_pygments: True
    - pymdownx.superfences
    - pymdownx.magiclink
    - md_in_html
    - markdown_link_attr_modifier:
          external_only: True
          custom_attrs:
              rel: "noopener"
              referrerpolicy: "origin"
plugins:
    - "include-markdown"
nav:
    - "Queue": index.md
